'use strict';
const KEY='flowwatch_v3_state', V2='flowwatch_v2_state';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const clone=x=>JSON.parse(JSON.stringify(x));
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const strip=html=>{const d=document.createElement('div');d.innerHTML=html||'';return (d.textContent||'').trim()};
const now=()=>Date.now(); const uid=()=>`${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
const fmtTime=sec=>{sec=Math.max(0,Math.round(sec||0));const m=Math.floor(sec/60),s=sec%60;return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`};
const pct=t=>Math.max(0,Math.min(100,Math.round(t.progressPct ?? (t.total?((t.seen||0)/t.total*100):0))));
const initials=t=>(t||'FW').split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase();
const statusLabel=s=>({watching:'En curso',planned:'Pendiente',finished:'Terminada'}[s]||s);
const typeLabel=t=>({anime:'Anime',series:'Serie',movie:'Película',documentary:'Documental'}[t]||'Título');
const humanAgo=ts=>{if(!ts)return 'Sin actividad';const d=(Date.now()-ts)/1000;if(d<60)return 'Ahora';if(d<3600)return `Hace ${Math.floor(d/60)} min`;if(d<86400)return `Hace ${Math.floor(d/3600)} h`;if(d<172800)return 'Ayer';return new Date(ts).toLocaleDateString('es-ES',{day:'numeric',month:'short'})};
const deviceKind=/iPhone|iPad|iPod/i.test(navigator.userAgent)?'iPhone':/Mac/i.test(navigator.platform)?'Mac':'PC';
const defaultState={version:3,revision:1,updatedAt:now(),deviceId:`${deviceKind.toLowerCase()}-${Math.random().toString(36).slice(2,7)}`,settings:{threshold:90,minSession:60,autoNext:true,antiSpoiler:true,autoSkip:true,offlineQueue:true,conflictMode:'smart'},titles:[
 {id:'fw-bleach',title:'Bleach',type:'anime',status:'watching',seen:63,total:366,currentEpisode:64,currentSeason:3,progressPct:52,positionSec:702,durationSec:1350,platform:'Skipper',updatedAt:now()-35*60*1000,lastWatchedAt:now()-35*60*1000,summary:'Ichigo Kurosaki obtiene poderes de shinigami y queda atrapado en conflictos entre el mundo humano y la Sociedad de Almas.',genres:['Action','Adventure'],year:2004,source:'Local demo'},
 {id:'fw-solo',title:'Solo Leveling',type:'anime',status:'watching',seen:18,total:25,currentEpisode:19,currentSeason:2,progressPct:22,positionSec:318,durationSec:1440,platform:'Skipper',updatedAt:now()-20*60*60*1000,lastWatchedAt:now()-20*60*60*1000,genres:['Action','Fantasy'],year:2024,source:'Local demo'},
 {id:'fw-tlou',title:'The Last of Us',type:'series',status:'watching',seen:12,total:16,currentEpisode:13,currentSeason:2,progressPct:0,positionSec:0,durationSec:3200,platform:'Max',updatedAt:now()-3*86400000,lastWatchedAt:now()-3*86400000,genres:['Drama','Thriller'],year:2023,source:'Local demo'},
 {id:'fw-homeland',title:'Homeland',type:'series',status:'finished',seen:96,total:96,currentEpisode:96,currentSeason:8,progressPct:100,positionSec:0,durationSec:3000,platform:'Finalizada',updatedAt:now()-5*86400000,lastWatchedAt:now()-5*86400000,genres:['Drama','Thriller'],year:2011,source:'Local demo'},
 {id:'fw-severance',title:'Severance',type:'series',status:'planned',seen:0,total:19,currentEpisode:1,currentSeason:1,progressPct:0,positionSec:0,durationSec:3000,platform:'Pendiente',updatedAt:now()-6*86400000,lastWatchedAt:0,genres:['Drama','Mystery'],year:2022,source:'Local demo'},
 {id:'fw-aot',title:'Attack on Titan',type:'anime',status:'finished',seen:94,total:94,currentEpisode:94,currentSeason:4,progressPct:100,positionSec:0,durationSec:1440,platform:'Finalizada',updatedAt:now()-7*86400000,lastWatchedAt:now()-7*86400000,genres:['Action','Drama'],year:2013,source:'Local demo'},
 {id:'fw-dark',title:'Dark',type:'series',status:'planned',seen:0,total:26,currentEpisode:1,currentSeason:1,progressPct:0,positionSec:0,durationSec:3000,platform:'Pendiente',updatedAt:now()-8*86400000,lastWatchedAt:0,genres:['Drama','Mystery'],year:2017,source:'Local demo'},
 {id:'fw-arcane',title:'Arcane',type:'series',status:'finished',seen:18,total:18,currentEpisode:18,currentSeason:2,progressPct:100,positionSec:0,durationSec:2400,platform:'Finalizada',updatedAt:now()-10*86400000,lastWatchedAt:now()-10*86400000,genres:['Action','Fantasy'],year:2021,source:'Local demo'}
],history:[
 {id:uid(),titleId:'fw-bleach',label:'Episodio 63 completado',action:'complete',progress:100,at:now()-35*60*1000,device:'iPhone · Skipper',minutes:22},
 {id:uid(),titleId:'fw-solo',label:'Episodio 18 completado',action:'complete',progress:100,at:now()-20*60*60*1000,device:'PC · navegador',minutes:24},
 {id:uid(),titleId:'fw-tlou',label:'S2 · episodio 4 completado',action:'complete',progress:100,at:now()-3*86400000,device:'TV / manual',minutes:49},
 {id:uid(),titleId:'fw-homeland',label:'Serie terminada',action:'complete',progress:100,at:now()-5*86400000,device:'PC',minutes:51}
],releases:[
 {id:uid(),date:new Date(Date.now()+2*86400000).toISOString().slice(0,10),title:'Bleach · episodio seguido',platform:'Seguimiento',titleId:'fw-bleach'},
 {id:uid(),date:new Date(Date.now()+4*86400000).toISOString().slice(0,10),title:'Solo Leveling · novedad',platform:'Seguimiento',titleId:'fw-solo'},
 {id:uid(),date:new Date(Date.now()+7*86400000).toISOString().slice(0,10),title:'Título de watchlist · estreno',platform:'Aviso'},
 {id:uid(),date:new Date(Date.now()+12*86400000).toISOString().slice(0,10),title:'Nueva temporada guardada',platform:'Calendario'}
],syncQueue:[],notifications:[
 {id:uid(),title:'Nuevo episodio',body:'Bleach tiene una novedad en tu seguimiento demo.',at:now()-20*60*1000,read:false},
 {id:uid(),title:'Progreso guardado',body:'Solo Leveling quedó sincronizado al 22 % del siguiente episodio.',at:now()-20*60*60*1000,read:false},
 {id:uid(),title:'Skipper Bridge',body:'Reproductor nativo: seguimiento automático disponible.',at:now()-2*86400000,read:false}
],health:{aniList:'unknown',tvmaze:'unknown',network:'unknown',cloud:'not-configured',checkedAt:0}};
function migrateV2(old){
 const s=clone(defaultState); if(!old||!Array.isArray(old.titles))return s;
 s.titles=old.titles.map((t,i)=>({id:`v2-${t.id??i}-${uid()}`,title:t.title||'Sin título',type:t.type||'series',status:t.status||'planned',seen:Number(t.seen)||0,total:Math.max(1,Number(t.total)||1),currentEpisode:Math.min(Math.max(1,(Number(t.seen)||0)+1),Math.max(1,Number(t.total)||1)),currentSeason:1,progressPct:t.status==='finished'?100:0,positionSec:0,durationSec:t.type==='anime'?1440:3000,platform:t.platform||'Importado V2',updatedAt:now()-i*60000,lastWatchedAt:0,cover:t.cover||'',year:t.year||'',genres:t.genres||[],rating:t.rating||'',summary:t.summary||'',source:t.source||'Migrado V2',sourceUrl:t.sourceUrl||'',externalId:t.externalId||null,metaFetchedAt:t.metaFetchedAt||0}));
 s.notifications.unshift({id:uid(),title:'Datos migrados',body:`Se han migrado ${s.titles.length} títulos desde WatchTower V2.`,at:now(),read:false});return s;
}
function load(){try{const raw=localStorage.getItem(KEY);if(raw){const s=JSON.parse(raw);if(s&&s.version===3&&Array.isArray(s.titles))return {...clone(defaultState),...s,settings:{...defaultState.settings,...s.settings}}}const old=localStorage.getItem(V2);if(old){const s=migrateV2(JSON.parse(old));localStorage.setItem(KEY,JSON.stringify(s));return s}}catch(e){}return clone(defaultState)}
let state=load(); let suppressBroadcast=false; let channel=null; try{channel=new BroadcastChannel('flowwatch_v3_tabs')}catch(e){}
function commit(reason='update',enqueue=true){state.revision=(state.revision||0)+1;state.updatedAt=now();try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){}if(enqueue&&state.settings.offlineQueue){state.syncQueue=state.syncQueue||[];state.syncQueue.push({id:uid(),reason,revision:state.revision,at:now(),device:state.deviceId});if(state.syncQueue.length>80)state.syncQueue=state.syncQueue.slice(-80);try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){}}if(channel&&!suppressBroadcast){try{channel.postMessage({type:'state',state,from:state.deviceId})}catch(e){}}renderChrome()}
function mergeIncoming(incoming){if(!incoming||incoming.version!==3)return;if((incoming.revision||0)<=(state.revision||0))return;suppressBroadcast=true;state=incoming;try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){}suppressBroadcast=false;renderAll();toast('Cambios sincronizados entre pestañas')}
if(channel)channel.onmessage=e=>{if(e.data?.type==='state'&&e.data.from!==state.deviceId)mergeIncoming(e.data.state)};
window.addEventListener('storage',e=>{if(e.key===KEY&&e.newValue){try{mergeIncoming(JSON.parse(e.newValue))}catch(_){}}});
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(()=>t.classList.remove('show'),2300)}
function cover(t){return t.cover?`<img src="${esc(t.cover)}" alt="" loading="lazy" referrerpolicy="no-referrer">`:initials(t.title)}
function getTitle(id){return state.titles.find(t=>t.id===id)}
function nav(view){$$('.view').forEach(v=>v.classList.remove('active'));$('#view-'+view)?.classList.add('active');$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));window.scrollTo({top:0,behavior:'smooth'});if(view==='calendar')renderCalendar();if(view==='library')renderLibrary();if(view==='activity')renderHistory();}
$$('[data-view]').forEach(b=>b.onclick=()=>nav(b.dataset.view));$$('[data-viewgo]').forEach(b=>b.onclick=()=>nav(b.dataset.viewgo));
function mostRecentWatching(){return [...state.titles].filter(t=>t.status==='watching').sort((a,b)=>(b.lastWatchedAt||b.updatedAt||0)-(a.lastWatchedAt||a.updatedAt||0))[0]||state.titles[0]}
function renderHero(){const t=mostRecentWatching();if(!t)return;$('#heroTitle').textContent=t.title;$('#heroMeta').textContent=t.type==='movie'?`${statusLabel(t.status)} · Película · ${pct(t)}% visto`:`${statusLabel(t.status)} · ${typeLabel(t.type)} · ${t.currentSeason?`T${t.currentSeason} · `:''}E${t.currentEpisode||Math.min(t.seen+1,t.total)} · ${t.seen}/${t.total} vistos`;$('#heroSummary').textContent=t.summary||'La sinopsis se completará automáticamente cuando la fuente de metadatos responda.';$('#heroProgress').style.width=`${pct(t)}%`;$('#heroProgressText').textContent=t.progressPct>0?`Episodio actual · ${pct(t)} %`:`${t.seen}/${t.total} episodios`;const remaining=Math.max(0,(t.durationSec||0)-(t.positionSec||0));$('#heroTimeText').textContent=t.progressPct>0?`${Math.round(remaining/60)} min restantes`:humanAgo(t.lastWatchedAt||t.updatedAt);$('#heroBg').style.backgroundImage=t.cover?`url("${String(t.cover).replace(/"/g,'%22')}")`:'none';$('#heroPlay').dataset.id=t.id;$('#heroPlusOne').dataset.id=t.id;$('#heroDetails').dataset.id=t.id;$('#heroPill').textContent=t.progressPct>0?'Reanudar episodio':'Siguiente episodio'}
function renderContinue(){const arr=[...state.titles].filter(t=>t.status==='watching').sort((a,b)=>(b.lastWatchedAt||b.updatedAt)-(a.lastWatchedAt||a.updatedAt));$('#continueGrid').innerHTML=arr.length?arr.map(t=>`<article class="continuecard" data-play="${esc(t.id)}"><div class="wideart">${t.cover?`<img src="${esc(t.cover)}" alt="" referrerpolicy="no-referrer">`:''}<span class="playmini">▶</span><span class="timebadge">${t.progressPct?`${pct(t)} %`:`E${t.currentEpisode}`}</span></div><div class="cardbody"><strong>${esc(t.title)}</strong><span>${t.currentSeason?`T${t.currentSeason} · `:''}E${t.currentEpisode} · ${humanAgo(t.lastWatchedAt||t.updatedAt)}</span><div class="microtrack"><i style="width:${pct(t)}%"></i></div></div></article>`).join(''):`<div class="empty"><strong>Nada a medias</strong>Cuando empieces algo aparecerá aquí.</div>`;$$('[data-play]').forEach(el=>el.onclick=()=>openPlayer(el.dataset.play))}
function renderStats(){const watching=state.titles.filter(t=>t.status==='watching').length;const weekAgo=now()-7*86400000;const week=state.history.filter(h=>h.at>=weekAgo&&h.action==='complete').length;const mins=state.history.reduce((a,h)=>a+(Number(h.minutes)||0),0);$('#statWatching').textContent=watching;$('#statWeek').textContent=week;$('#statMinutes').textContent=mins>=60?`${Math.floor(mins/60)}h ${mins%60}m`:`${mins}m`;$('#statQueue').textContent=state.syncQueue.length;$('#statNet').textContent=navigator.onLine?'Online':'Offline'}
function renderRecent(){const rows=[...state.history].sort((a,b)=>b.at-a.at).slice(0,5);$('#recentActivity').innerHTML=rows.length?rows.map(h=>{const t=getTitle(h.titleId)||{title:'Título eliminado'};return `<div class="rowitem"><div class="smallposter">${t.cover?`<img src="${esc(t.cover)}" alt="">`:initials(t.title)}</div><div><b>${esc(t.title)}</b><span>${esc(h.label)} · ${h.progress??0}%</span></div><div class="rowright">${humanAgo(h.at)}<br>${esc(h.device||'Local')}</div></div>`}).join(''):`<div class="empty">Sin actividad todavía.</div>`}
function releaseRow(r){const d=new Date(r.date+'T12:00:00');const mons=['ENE','FEB','MAR','ABR','MAY','JUN','JUL','AGO','SEP','OCT','NOV','DIC'];return `<div class="rowitem"><div class="datebox"><div><b>${d.getDate()}</b><small>${mons[d.getMonth()]}</small></div></div><div><b>${esc(r.title)}</b><span>${esc(r.platform||'Seguimiento')}</span></div><div class="rowright">${d.toLocaleDateString('es-ES',{weekday:'short'})}</div></div>`}
function renderWeek(){const start=new Date();start.setHours(0,0,0,0);const end=new Date(start);end.setDate(end.getDate()+7);const arr=state.releases.filter(r=>{const d=new Date(r.date+'T12:00:00');return d>=start&&d<=end}).slice(0,5);$('#weekReleases').innerHTML=arr.length?arr.map(releaseRow).join(''):`<div class="empty"><strong>Sin estrenos cercanos</strong>Actualiza tus fichas para buscar novedades.</div>`}
let currentFilter='all', currentSort='recent';