'use strict';
window.addEventListener('online',()=>{state.health.network='ok';renderChrome();renderHealth();toast('Conexión recuperada')});window.addEventListener('offline',()=>{state.health.network='offline';renderChrome();renderHealth();toast('Modo offline activado')});
$$('[data-setting]').forEach(b=>b.onclick=()=>{const k=b.dataset.setting;b.classList.toggle('on');state.settings[k]=b.classList.contains('on');commit(`setting-${k}`,false);toast(state.settings[k]?'Ajuste activado':'Ajuste desactivado')});$('#threshold').value=state.settings.threshold;$('#thresholdText').textContent=`${state.settings.threshold} %`;$('#threshold').oninput=e=>{$('#thresholdText').textContent=`${e.target.value} %`};$('#threshold').onchange=e=>{state.settings.threshold=Number(e.target.value);commit('threshold',false)};$('#minSession').value=String(state.settings.minSession);$('#minSession').onchange=e=>{state.settings.minSession=Number(e.target.value);commit('min-session',false)};$('#conflictMode').value=state.settings.conflictMode;$('#conflictMode').onchange=e=>{state.settings.conflictMode=e.target.value;commit('conflict-mode',false)};
function flushQueue(){if(!navigator.onLine){toast('Sin conexión: la cola se conserva');return}const count=state.syncQueue.length;state.syncQueue=[];commit('queue-flush',false);renderAll();toast(count?`${count} eventos procesados localmente`:'La cola ya estaba vacía')}$('#flushQueue').onclick=flushQueue;$('#syncBtn').onclick=()=>{nav('integrations');testHealth()};$('#simulateConflict').onclick=()=>{const t=mostRecentWatching();if(!t){toast('Añade un título antes de simular un conflicto');return}const old=t.progressPct;t.progressPct=Math.max(old,Math.min(99,old+7));t.updatedAt=now()+1000;state.notifications.unshift({id:uid(),title:'Conflicto resuelto',body:`${t.title}: se conservó el progreso mayor (${t.progressPct} %).`,at:now(),read:false});commit('conflict-sim');renderAll();toast('Conflicto simulado y resuelto')};
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`watchtower-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}$('#exportData').onclick=exportData;$('#importData').onclick=()=>$('#importFile').click();$('#importFile').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{const x=JSON.parse(await f.text());if(!x||x.version!==3||!Array.isArray(x.titles))throw new Error();state={...clone(defaultState),...x,profile:{...defaultState.profile,...(x.profile||{})},settings:{...defaultState.settings,...x.settings},deviceId:state.deviceId,revision:Math.max(state.revision||0,x.revision||0)+1,updatedAt:now()};commit('backup-import',false);renderAll();toast('Copia importada')}catch(_){toast('Ese archivo no es una copia válida de WatchTower')}e.target.value=''};$('#resetData').onclick=()=>{const keepProfile={...defaultState.profile,...(state.profile||{})};state=clone(defaultState);state.profile=keepProfile;state.deviceId=`${deviceKind.toLowerCase()}-${Math.random().toString(36).slice(2,7)}`;commit('reset',false);renderAll();toast('Datos locales restablecidos')};$('#installHelp').onclick=()=>toast(deviceKind==='iPhone'?'Safari → Compartir → Añadir a pantalla de inicio':'Con HTTPS: menú del navegador → Instalar WatchTower');
$('#refreshMeta').onclick=()=>hydrateAll(true);
function renderProfile(){const name=String(state.profile?.displayName||'').trim();const welcome=$('#welcomeTitle');if(welcome)welcome.textContent=name?`Buenas, ${name}`:'Buenas';const btn=document.querySelector('.profilebtn');if(btn){const av=btn.querySelector('.avatar');const label=btn.querySelector('.profilelabel');if(av)av.textContent=name?initials(name):'WT';if(label)label.textContent=name||'Mi perfil'}}
function saveProfile(name,setupDone=true){state.profile={...defaultState.profile,...(state.profile||{}),displayName:String(name||'').trim().slice(0,40),setupDone:!!setupDone};commit('profile',false);renderProfile()}
function openProfileSetup(){const m=$('#welcomeModal');if(!m)return;$('#profileName').value=state.profile?.displayName||'';m.classList.add('open');setTimeout(()=>$('#profileName')?.focus(),60)}
function initProfileSetup(){renderProfile();if(!state.profile?.setupDone)setTimeout(openProfileSetup,350)}
function renderAll(){renderHero();renderContinue();renderStats();renderRecent();renderWeek();renderLibrary();renderCalendar();renderHistory();renderHealth();renderChrome();renderProfile()}
document.querySelector('.profilebtn')?.addEventListener('click',openProfileSetup);$('#welcomeStart')?.addEventListener('click',()=>{saveProfile($('#profileName').value,true);$('#welcomeModal').classList.remove('open');toast('WatchTower preparado')});$('#welcomeSkip')?.addEventListener('click',()=>{saveProfile('',true);$('#welcomeModal').classList.remove('open')});$('#profileName')?.addEventListener('keydown',e=>{if(e.key==='Enter')$('#welcomeStart')?.click()});
$$('.modalback').forEach(m=>m.addEventListener('click',e=>{if(e.target===m){if(m.id==='playerModal'&&player.playing)setPlaying(false);m.classList.remove('open')}}));

// ================= FLOWWATCH V4 ADDONS =================
const V4CFGKEY='flowwatch_v4_config', V4SESSIONKEY='flowwatch_v4_cloud_session';
function v4cfg(){try{return {...{tmdbToken:'',supabaseUrl:'',supabaseAnonKey:'',email:''},...JSON.parse(localStorage.getItem(V4CFGKEY)||'{}')}}catch(_){return {tmdbToken:'',supabaseUrl:'',supabaseAnonKey:'',email:''}}}
function saveV4cfg(p){const n={...v4cfg(),...p};localStorage.setItem(V4CFGKEY,JSON.stringify(n));return n}
function ensureV4(){state.v4=state.v4||{};state.v4.profile={enabledTypes:{anime:true,series:true,movie:true,documentary:false},weights:{anime:5,series:4,movie:3,documentary:1},genres:['Action','Thriller','Sci-Fi','Mystery'],services:['Skipper','Netflix'],modules:['continue','foryou','activity','releases'],theme:'navy',density:'comfortable',heroIntensity:75,hideFinishedHome:true,...(state.v4.profile||{})};state.v4.processedEvents=Array.isArray(state.v4.processedEvents)?state.v4.processedEvents:[];state.v4.extension=state.v4.extension||{connected:false,lastHeartbeat:0,lastEvent:null};state.v4.cloud=state.v4.cloud||{status:'off',lastSync:0};}
ensureV4();
function injectV4UI(){
 const side=$('.nav'); if(side&&!$('#v4PersonalNav')){const b=document.createElement('button');b.id='v4PersonalNav';b.dataset.view='personalize';b.innerHTML='<svg viewBox="0 0 24 24" fill="none"><path d="M4 7h10M4 17h16M14 7h6M4 12h16" stroke="currentColor" stroke-width="1.6"/><circle cx="11" cy="7" r="2" stroke="currentColor" stroke-width="1.5"/><circle cx="8" cy="17" r="2" stroke="currentColor" stroke-width="1.5"/></svg>Personalizar';const integ=[...side.querySelectorAll('button')].find(x=>x.dataset.view==='integrations');side.insertBefore(b,integ||null);b.onclick=()=>nav('personalize')}
 if(!$('#view-personalize')){const sec=document.createElement('section');sec.className='view';sec.id='view-personalize';sec.innerHTML=`
 <div class="viewhead"><div><div class="eyebrow">Tu WatchTower, no el de todo el mundo</div><h1>Personalización</h1><p>Misma estructura, pero portada, prioridades y descubrimiento adaptados a lo que realmente ves.</p></div><div class="actions"><button class="secondary" id="v4ResetPrefs">Restablecer</button></div></div>
 <div class="v4grid">
  <div class="card v4card"><h3>Qué quieres ver</h3><p>Activa categorías y decide cuánto peso tiene cada una en Inicio y Descubrir.</p><div class="togglechips" id="v4Types"></div><div id="v4Weights"></div></div>
  <div class="card v4card"><h3>Géneros favoritos</h3><p>WatchTower los usa para ordenar tu estantería «Para ti». No cambia tu biblioteca.</p><div class="genrechips" id="v4Genres"></div></div>
  <div class="card v4card"><h3>Servicios que usas</h3><p>Sirve para priorizar integraciones y dejar a mano los orígenes más útiles.</p><div class="servicechips" id="v4Services"></div></div>
  <div class="card v4card"><h3>Inicio modular</h3><p>Puedes activar y ordenar los bloques sin cargarte la estructura base.</p><div class="modulelist" id="v4Modules"></div></div>
  <div class="card v4card"><h3>Apariencia</h3><p>Flow táctico por defecto, pero sin obligarte a usar siempre el mismo acento.</p><div class="accentrow" id="v4Accents"></div><div class="settingrow"><div><strong>Densidad compacta</strong><span>Más contenido, menos aire.</span></div><button class="switch" id="v4Density"><i></i></button></div><div class="settingrow"><div><strong>Intensidad del hero</strong><span id="v4HeroText">75 %</span></div><input class="range" id="v4HeroIntensity" type="range" min="35" max="100" value="75"></div></div>
  <div class="card v4card"><h3>Portadas de películas · TMDB</h3><p>Anime usa AniList y series TVmaze. Para películas puedes añadir tu token de lectura de TMDB.</p><label class="v4label">TMDB API key o Read Access Token</label><input class="v4input" id="v4Tmdb" placeholder="Opcional · se guarda solo en este navegador"><div class="v4help">Sin token, WatchTower sigue funcionando; simplemente no consulta películas en TMDB automáticamente.</div></div>
 </div>`;$('#view-integrations').before(sec)}
 const set=$('#view-settings .settingsgrid'); if(set&&!$('#v4MobileCustomize')){const d=document.createElement('div');d.id='v4MobileCustomize';d.className='card settinggroup mobile-customize';d.innerHTML='<h3>Personalización</h3><p>En iPhone la barra inferior se mantiene limpia.</p><button class="secondary" id="v4GoPersonal">Abrir personalización</button>';set.prepend(d);$('#v4GoPersonal').onclick=()=>nav('personalize')}
 const integ=$('#view-integrations'); if(integ&&!$('#v4Connectivity')){const wrap=document.createElement('div');wrap.id='v4Connectivity';wrap.className='section v4grid';wrap.innerHTML=`
 <div class="card v4card"><div style="display:flex;justify-content:space-between;gap:10px"><div><h3>Extensión WatchTower</h3><p>Netflix/Disney+/Prime en PC → eventos de reproducción → centro de control.</p></div><span class="livepill warn" id="v4ExtPill"><i class="statusdot"></i>Sin detectar</span></div><div class="connectionbar"><div><b>Última captura</b><span id="v4ExtLast">Todavía ninguna</span></div><button class="secondary" id="v4PingExt">Probar puente</button></div><div class="v4help">Si el centro está cerrado, la extensión guarda una cola. Con nube configurada, también puede enviar los eventos directamente.</div></div>
 <div class="card v4card"><h3>WatchTower Cloud · Supabase</h3><p>Es el puente PC ↔ iPhone. Crea tu proyecto, ejecuta <b>supabase/schema.sql</b> y pega aquí los datos públicos del proyecto.</p><div class="formrow"><div><label class="v4label">Project URL</label><input class="v4input" id="v4SbUrl" placeholder="https://xxxx.supabase.co"></div><div><label class="v4label">Anon key</label><input class="v4input" id="v4SbKey" placeholder="anon/public key"></div></div><div class="formrow"><div><label class="v4label">Email</label><input class="v4input" id="v4SbEmail" type="email"></div><div><label class="v4label">Contraseña</label><input class="v4input" id="v4SbPass" type="password" placeholder="No se guarda"></div></div><div class="actions" style="margin-top:10px"><button class="secondary" id="v4SignUp">Crear cuenta</button><button class="primary" id="v4SignIn">Entrar</button><button class="secondary" id="v4CloudSync">Sincronizar ahora</button><button class="ghost" id="v4SignOut">Salir</button></div><div class="connectionbar"><div><b>Estado nube</b><span id="v4CloudText">Sin configurar</span></div><span class="livepill warn" id="v4CloudPill"><i class="statusdot"></i>Offline</span></div></div>`;integ.append(wrap)}
 const home=$('#view-home'); if(home&&!$('#v4PersonalShelf')){const shelf=document.createElement('div');shelf.id='v4PersonalShelf';shelf.className='personal-shelf';const anchor=home.querySelector('.homegrid');home.insertBefore(shelf,anchor)}
 bindV4UI();renderV4();
}
function bindV4UI(){
 const genres=['Action','Thriller','Sci-Fi','Fantasy','Mystery','Drama','Comedy','Romance','Crime','Documentary'];const services=['Skipper','Netflix','Prime Video','Disney+','Max','Crunchyroll','Apple TV+'];
 $('#v4ResetPrefs').onclick=()=>{state.v4.profile={enabledTypes:{anime:true,series:true,movie:true,documentary:false},weights:{anime:5,series:4,movie:3,documentary:1},genres:['Action','Thriller','Sci-Fi','Mystery'],services:['Skipper','Netflix'],modules:['continue','foryou','activity','releases'],theme:'navy',density:'comfortable',heroIntensity:75,hideFinishedHome:true};commit('v4-prefs-reset',false);renderV4();toast('Personalización restablecida')};
 $('#v4Tmdb').value=v4cfg().tmdbToken||'';$('#v4Tmdb').onchange=e=>{saveV4cfg({tmdbToken:e.target.value.trim()});toast('TMDB guardado en este navegador')};
 $('#v4Density').onclick=()=>{state.v4.profile.density=state.v4.profile.density==='compact'?'comfortable':'compact';commit('v4-density',false);renderV4()};
 $('#v4HeroIntensity').oninput=e=>{$('#v4HeroText').textContent=`${e.target.value} %`;state.v4.profile.heroIntensity=Number(e.target.value);applyV4Visuals()};$('#v4HeroIntensity').onchange=()=>commit('v4-hero',false);
 $('#v4PingExt').onclick=()=>{window.postMessage({source:'FLOWWATCH_WEB',type:'HELLO'},'*');window.postMessage({source:'FLOWWATCH_WEB',type:'PULL_EVENTS'},'*');toast('Buscando extensión…')};
 const cfg=v4cfg();$('#v4SbUrl').value=cfg.supabaseUrl||'';$('#v4SbKey').value=cfg.supabaseAnonKey||'';$('#v4SbEmail').value=cfg.email||'';
 const saveCloudFields=()=>saveV4cfg({supabaseUrl:$('#v4SbUrl').value.trim().replace(/\/$/,''),supabaseAnonKey:$('#v4SbKey').value.trim(),email:$('#v4SbEmail').value.trim()});['v4SbUrl','v4SbKey','v4SbEmail'].forEach(id=>$('#'+id).onchange=saveCloudFields);
 $('#v4SignIn').onclick=()=>cloudAuth(false);$('#v4SignUp').onclick=()=>cloudAuth(true);$('#v4SignOut').onclick=()=>{localStorage.removeItem(V4SESSIONKEY);state.v4.cloud.status='off';renderV4Cloud();window.postMessage({source:'FLOWWATCH_WEB',type:'CLOUD_CONFIG',config:null},'*');toast('Sesión cloud cerrada')};$('#v4CloudSync').onclick=()=>cloudSync(true);
}
